server:
  port: 8761 # Port for Eureka Server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false # Disable self-preservation mode
